name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Build
      run: go build -v

    - name: Update repos
      run: sudo apt-get update

    - name: Install yt-dlp
      run: sudo apt-get install -y yt-dlp

    - name: Test
      run: go test -v
